# Generated by Django 3.2.5 on 2021-07-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_alter_comment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
    ]
