# Generated by Django 3.2.5 on 2021-07-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_remove_comment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.CharField(default='Your message', max_length=55),
        ),
    ]
