# Generated by Django 3.2.5 on 2021-07-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_auto_20210719_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(default='', max_length=208),
        ),
    ]
